import { ErrorPatternGroup } from "../../../types/errorHandling/error-handler.types";

export default class FrontendErrorPatterns {
  public static readonly UI_AND_BROWSER: ErrorPatternGroup = {
    category: "UI_AND_BROWSER",
    context: "UI and Browser Error",
    patterns: [
      // Test Lifecycle: TEST, SETUP, TEARDOWN, FIXTURE
      /\btest\s+(?:failed|error|crash|timeout)\b/i,
      /\btest\s+(?:execution|run|case)\s+(?:failed|error|timeout|skipped)\b/i,
      /\btest\s+(?:assertion|validation|check)\s+(?:failed|error|mismatch)\b/i,

      /\bsetup\s+(?:failed|error|crash|timeout)\b/i,
      /\btest\s+setup\s+(?:failed|error|timeout|not\s+run)\b/i,

      /\bteardown\s+(?:failed|error|crash|timeout)\b/i,
      /\btest\s+teardown\s+(?:failed|error|timeout|not\s+run)\b/i,

      /\bfixture\s+(?:failed|error|timeout|missing|invalid)\b/i,
      /\btest\s+fixture\s+(?:load|init|setup)\s+(?:failed|error|timeout)\b/i,

      // Retry & Expected Failure
      /\bretry\s+(?:limit|attempts|count)\s+(?:exceeded|reached)\b/i,
      /\bretry\s+(?:exhausted|failed|error)\b/i,
      /\bretry\s+(?:timeout|abort|gave\s+up)\b/i,

      /\bexpected\s+failure\b/i,
      /\btest\s+(?:marked|tagged)\s+as\s+expected\s+failure\b/i,
      /\bexpected\s+to\s+fail\s+but\s+passed\b/i,
      /\bexpected\s+to\s+fail\s+and\s+failed\b/i,

      // Browser & Pages
      /\bbrowser\s+(?:launch|start|open)\s+(?:failed|error|timeout)\b/i,
      /\bbrowser\s+(?:crash|crashed|died|killed)\b/i,
      /\bbrowser\s+(?:not\s+responding|frozen|hang|stuck)\b/i,
      /\bchrome\s+(?:error|crash|failed|timeout)\b/i,
      /\bfirefox\s+(?:error|crash|failed|timeout)\b/i,
      /\bsafari\s+(?:error|crash|failed|timeout)\b/i,
      /\bedge\s+(?:error|crash|failed|timeout)\b/i,
      /\bwebdriver\s+(?:error|failed|timeout|exception)\b/i,
      /\bpuppeteer\s+(?:error|failed|timeout|crash)\b/i,
      /\bplaywright\s+(?:error|failed|timeout|crash)\b/i,
      /\bselenium\s+(?:error|failed|timeout|crash)\b/i,
      /\bpage\s+(?:load|loading)\s+(?:failed|error|timeout)\b/i,
      /\bpage\s+(?:not\s+found|404|error|crash)\b/i,
      /\bpage\s+(?:reload|refresh)\s+(?:failed|error|timeout)\b/i,
      /\bpage\s+(?:navigation|goto)\s+(?:failed|error|timeout)\b/i,
      /\bpage\s+(?:evaluation|execute)\s+(?:failed|error|timeout)\b/i,
      /\bpage\s+(?:script|javascript)\s+(?:error|failed|timeout)\b/i,
      /\bpage\s+(?:content|response)\s+(?:error|failed|timeout)\b/i,
      /\bpage\s+(?:ready|complete)\s+(?:timeout|failed)\b/i,
      /\bnavigation\s+(?:failed|error|timeout)\b/i,
      /\bnavigate\s+(?:to|back|forward)\s+(?:failed|error|timeout)\b/i,
      /\burl\s+(?:navigation|load|access)\s+(?:failed|error|timeout)\b/i,
      /\bgo\s+(?:to|back|forward)\s+(?:failed|error|timeout)\b/i,
      /\bhistory\s+(?:navigation|back|forward)\s+(?:failed|error)\b/i,
      /\broute\s+(?:navigation|change)\s+(?:failed|error|timeout)\b/i,
      /\bnavigation\s+(?:intercepted|blocked|cancelled)\b/i,
      /\bnet::ERR_.*(?:navigation|load|access)\b/i,
      /\bframe\s+(?:not\s+found|missing|invalid)\b/i,
      /\bframe\s+(?:load|loading)\s+(?:failed|error|timeout)\b/i,
      /\bframe\s+(?:switch|access)\s+(?:failed|error|timeout)\b/i,
      /\bframe\s+(?:detached|destroyed|invalid)\b/i,
      /\bframe\s+(?:content|execution)\s+(?:failed|error|timeout)\b/i,
      /\biframe\s+(?:not\s+found|missing|invalid)\b/i,
      /\biframe\s+(?:load|loading)\s+(?:failed|error|timeout)\b/i,
      /\biframe\s+(?:switch|access)\s+(?:failed|error|timeout)\b/i,
      /\biframe\s+(?:detached|destroyed|invalid)\b/i,
      /\biframe\s+(?:content|execution)\s+(?:failed|error|timeout)\b/i,
      /\biframe\s+(?:security|cross-origin)\s+(?:error|violation)\b/i,
      /\bframe\s+(?:timeout|wait|loading)\s+(?:exceeded|failed|error)\b/i,
      /\biframe\s+(?:timeout|wait|loading)\s+(?:exceeded|failed|error)\b/i,
      /\bframe\s+(?:ready|complete)\s+(?:timeout|failed)\b/i,
      /\bframe\s+(?:response|load)\s+(?:timeout|slow|exceeded)\b/i,

      // Elements & Selectors
      /\belement\s+(?:not\s+found|missing|invalid)\b/i,
      /\belement\s+(?:not\s+visible|hidden|invisible)\b/i,
      /\belement\s+(?:not\s+interactable|disabled|readonly)\b/i,
      /\belement\s+(?:stale|detached|invalid)\b/i,
      /\belement\s+(?:click|tap|select)\s+(?:failed|error|timeout)\b/i,
      /\belement\s+(?:input|type|fill)\s+(?:failed|error|timeout)\b/i,
      /\belement\s+(?:scroll|focus|blur)\s+(?:failed|error|timeout)\b/i,
      /\belement\s+(?:attribute|property|text)\s+(?:error|failed|missing)\b/i,
      /\blocator\s+(?:not\s+found|invalid|failed)\b/i,
      /\blocator\s+(?:timeout|wait|exceeded)\b/i,
      /\blocator\s+(?:multiple|ambiguous|duplicate)\s+(?:elements|matches)\b/i,
      /\blocator\s+(?:strategy|method)\s+(?:invalid|failed|error)\b/i,
      /\blocator\s+(?:resolution|evaluation)\s+(?:failed|error|timeout)\b/i,
      /\bselector\s+(?:invalid|malformed|syntax)\s+(?:error|failed)\b/i,
      /\bselector\s+(?:not\s+found|missing|failed)\b/i,
      /\bselector\s+(?:timeout|wait|exceeded)\b/i,
      /\bcss\s+selector\s+(?:invalid|error|failed)\b/i,
      /\bxpath\s+(?:invalid|error|failed|syntax)\b/i,
      /\bquery\s+selector\s+(?:invalid|error|failed)\b/i,
      /\bselector\s+(?:multiple|ambiguous)\s+(?:elements|matches)\b/i,
      /\bwait\s+(?:condition|for)\s+(?:timeout|failed|error)\b/i,
      /\bwait\s+(?:until|for)\s+(?:visible|clickable|present)\s+(?:timeout|failed)\b/i,
      /\bwait\s+(?:until|for)\s+(?:text|attribute|value)\s+(?:timeout|failed)\b/i,
      /\bwait\s+(?:until|for)\s+(?:element|locator)\s+(?:timeout|failed)\b/i,
      /\bexpected\s+condition\s+(?:timeout|failed|error)\b/i,
      /\bwait\s+(?:timeout|exceeded|failed)\b/i,
      /\bimplicit\s+wait\s+(?:timeout|failed|error)\b/i,
      /\bexplicit\s+wait\s+(?:timeout|failed|error)\b/i,
      /\belement\s+(?:not\s+in\s+expected|wrong|invalid)\s+state\b/i,
      /\belement\s+(?:not\s+enabled|disabled|readonly)\b/i,
      /\belement\s+(?:not\s+visible|hidden|invisible|obscured)\b/i,
      /\belement\s+(?:not\s+clickable|not\s+interactable)\b/i,
      /\belement\s+(?:not\s+selected|unselected|deselected)\b/i,
      /\belement\s+(?:not\s+checked|unchecked)\b/i,
      /\belement\s+(?:state\s+change|transition)\s+(?:failed|timeout|error)\b/i,

      // User Interaction
      /\bkeyboard\s+(?:input|type|press)\s+(?:failed|error|timeout)\b/i,
      /\bkey\s+(?:press|down|up|combination)\s+(?:failed|error|timeout)\b/i,
      /\btype\s+(?:text|input|keys)\s+(?:failed|error|timeout)\b/i,
      /\bsend\s+keys\s+(?:failed|error|timeout)\b/i,
      /\bkeyboard\s+(?:shortcut|combination)\s+(?:failed|error|timeout)\b/i,
      /\benter\s+(?:key|text|input)\s+(?:failed|error|timeout)\b/i,
      /\btab\s+(?:key|navigation)\s+(?:failed|error|timeout)\b/i,
      /\bkeyboard\s+(?:event|action)\s+(?:failed|error|timeout)\b/i,
      /\bmouse\s+(?:click|move|action)\s+(?:failed|error|timeout)\b/i,
      /\bclick\s+(?:action|event)\s+(?:failed|error|timeout)\b/i,
      /\bdouble\s+click\s+(?:failed|error|timeout)\b/i,
      /\bright\s+click\s+(?:failed|error|timeout)\b/i,
      /\bmouse\s+(?:move|position|coordinates)\s+(?:failed|error|timeout)\b/i,
      /\bmouse\s+(?:over|enter|leave)\s+(?:failed|error|timeout)\b/i,
      /\bmouse\s+(?:down|up|press|release)\s+(?:failed|error|timeout)\b/i,
      /\bmouse\s+(?:wheel|scroll)\s+(?:failed|error|timeout)\b/i,
      /\bhover\s+(?:action|event)\s+(?:failed|error|timeout)\b/i,
      /\bmouse\s+(?:hover|over)\s+(?:failed|error|timeout)\b/i,
      /\bhover\s+(?:element|target)\s+(?:failed|error|timeout)\b/i,
      /\bhover\s+(?:state|effect)\s+(?:failed|error|timeout)\b/i,
      /\bhover\s+(?:menu|tooltip|dropdown)\s+(?:failed|error|timeout)\b/i,
      /\bgesture\s+(?:action|event)\s+(?:failed|error|timeout)\b/i,
      /\btouch\s+(?:action|event|gesture)\s+(?:failed|error|timeout)\b/i,
      /\bswipe\s+(?:action|gesture)\s+(?:failed|error|timeout)\b/i,
      /\bpinch\s+(?:action|gesture)\s+(?:failed|error|timeout)\b/i,
      /\bzoom\s+(?:action|gesture)\s+(?:failed|error|timeout)\b/i,
      /\brotate\s+(?:action|gesture)\s+(?:failed|error|timeout)\b/i,
      /\btap\s+(?:action|gesture)\s+(?:failed|error|timeout)\b/i,
      /\blong\s+press\s+(?:action|gesture)\s+(?:failed|error|timeout)\b/i,
      /\bdrag\s+(?:and\s+drop|drop)\s+(?:failed|error|timeout)\b/i,
      /\bdrag\s+(?:action|operation)\s+(?:failed|error|timeout)\b/i,
      /\bdrop\s+(?:action|operation)\s+(?:failed|error|timeout)\b/i,
      /\bdrag\s+(?:start|end|move)\s+(?:failed|error|timeout)\b/i,
      /\bdrop\s+(?:target|zone)\s+(?:failed|error|invalid)\b/i,
      /\bdrag\s+(?:source|element)\s+(?:failed|error|invalid)\b/i,
      /\bdialog\s+(?:not\s+found|missing|closed)\b/i,
      /\bdialog\s+(?:accept|dismiss|close)\s+(?:failed|error|timeout)\b/i,
      /\balert\s+(?:accept|dismiss|close)\s+(?:failed|error|timeout)\b/i,
      /\bconfirm\s+(?:accept|dismiss|close)\s+(?:failed|error|timeout)\b/i,
      /\bprompt\s+(?:accept|dismiss|input)\s+(?:failed|error|timeout)\b/i,
      /\bmodal\s+(?:dialog|window)\s+(?:failed|error|timeout)\b/i,
      /\bpopup\s+(?:dialog|window)\s+(?:failed|error|timeout)\b/i,

      // Files & Media
      /\bscreenshot\s+(?:capture|take|save)\s+(?:failed|error|timeout)\b/i,
      /\bscreen\s+(?:capture|shot|image)\s+(?:failed|error|timeout)\b/i,
      /\bimage\s+(?:capture|save|export)\s+(?:failed|error|timeout)\b/i,
      /\bscreenshot\s+(?:path|file|directory)\s+(?:invalid|error|failed)\b/i,
      /\bscreenshot\s+(?:quality|format|size)\s+(?:error|invalid|failed)\b/i,
      /\bfullpage\s+screenshot\s+(?:failed|error|timeout)\b/i,
      /\bdownload\s+(?:failed|error|timeout|cancelled)\b/i,
      /\bfile\s+download\s+(?:failed|error|timeout|cancelled)\b/i,
      /\bdownload\s+(?:path|directory|location)\s+(?:invalid|error|failed)\b/i,
      /\bdownload\s+(?:interrupted|incomplete|corrupted)\b/i,
      /\bdownload\s+(?:permission|access)\s+(?:denied|error|failed)\b/i,
      /\bdownload\s+(?:progress|status)\s+(?:error|failed|unknown)\b/i,
      /\bupload\s+(?:failed|error|timeout|cancelled)\b/i,
      /\bfile\s+upload\s+(?:failed|error|timeout|cancelled)\b/i,
      /\bupload\s+(?:path|file|location)\s+(?:invalid|error|not\s+found)\b/i,
      /\bupload\s+(?:interrupted|incomplete|corrupted)\b/i,
      /\bupload\s+(?:permission|access)\s+(?:denied|error|failed)\b/i,
      /\bupload\s+(?:size|limit|quota)\s+(?:exceeded|error|failed)\b/i,
      /\bfile\s+(?:input|selection)\s+(?:failed|error|timeout)\b/i,

      // Visual/UI Style
      /\bscroll\s+(?:action|operation)\s+(?:failed|error|timeout)\b/i,
      /\bscroll\s+(?:to|into\s+view)\s+(?:failed|error|timeout)\b/i,
      /\bscroll\s+(?:up|down|left|right)\s+(?:failed|error|timeout)\b/i,
      /\bscroll\s+(?:position|offset)\s+(?:failed|error|invalid)\b/i,
      /\bscroll\s+(?:element|container)\s+(?:failed|error|not\s+found)\b/i,
      /\bscrollable\s+(?:area|element)\s+(?:failed|error|not\s+found)\b/i,
      /\bscroll\s+(?:behavior|animation)\s+(?:failed|error|timeout)\b/i,
      /\btext\s+(?:verification|validation)\s+(?:failed|error|mismatch)\b/i,
      /\btext\s+(?:content|value)\s+(?:mismatch|different|incorrect)\b/i,
      /\btext\s+(?:not\s+found|missing|absent)\b/i,
      /\btext\s+(?:comparison|match)\s+(?:failed|error|timeout)\b/i,
      /\bexpected\s+text\s+(?:not\s+found|mismatch|different)\b/i,
      /\bactual\s+text\s+(?:different|mismatch|incorrect)\b/i,
      /\btext\s+(?:assertion|check)\s+(?:failed|error|timeout)\b/i,
      /\bcontent\s+(?:mismatch|different|incorrect)\b/i,
      /\bcontent\s+(?:verification|validation)\s+(?:failed|error|mismatch)\b/i,
      /\bcontent\s+(?:not\s+found|missing|absent)\b/i,
      /\bcontent\s+(?:comparison|match)\s+(?:failed|error|timeout)\b/i,
      /\bexpected\s+content\s+(?:not\s+found|mismatch|different)\b/i,
      /\bactual\s+content\s+(?:different|mismatch|incorrect)\b/i,
      /\bcontent\s+(?:assertion|check)\s+(?:failed|error|timeout)\b/i,
      /\bhtml\s+content\s+(?:mismatch|different|incorrect)\b/i,

      // Browser Tabs & Contexts
      /\btab\s+(?:not\s+found|missing|closed)\b/i,
      /\btab\s+(?:switch|change|activate)\s+(?:failed|error|timeout)\b/i,
      /\btab\s+(?:open|create|new)\s+(?:failed|error|timeout)\b/i,
      /\btab\s+(?:close|kill|terminate)\s+(?:failed|error|timeout)\b/i,
      /\btab\s+(?:handle|reference|id)\s+(?:invalid|error|failed)\b/i,
      /\btab\s+(?:focus|blur|activate)\s+(?:failed|error|timeout)\b/i,
      /\bwindow\s+(?:not\s+found|missing|closed)\b/i,
      /\bwindow\s+(?:switch|change|activate)\s+(?:failed|error|timeout)\b/i,
      /\bwindow\s+(?:open|create|new)\s+(?:failed|error|timeout)\b/i,
      /\bwindow\s+(?:close|kill|terminate)\s+(?:failed|error|timeout)\b/i,
      /\bwindow\s+(?:handle|reference|id)\s+(?:invalid|error|failed)\b/i,
      /\bwindow\s+(?:focus|blur|activate)\s+(?:failed|error|timeout)\b/i,
      /\bwindow\s+(?:resize|maximize|minimize)\s+(?:failed|error|timeout)\b/i,
      /\bwindow\s+(?:position|location|coordinates)\s+(?:failed|error|invalid)\b/i,
      /\bcontext\s+(?:not\s+found|missing|invalid)\b/i,
      /\bcontext\s+(?:switch|change|activate)\s+(?:failed|error|timeout)\b/i,
      /\bcontext\s+(?:create|new|initialization)\s+(?:failed|error|timeout)\b/i,
      /\bcontext\s+(?:close|destroy|terminate)\s+(?:failed|error|timeout)\b/i,
      /\bcontext\s+(?:isolation|security)\s+(?:failed|error|violation)\b/i,
      /\bbrowser\s+context\s+(?:failed|error|timeout|invalid)\b/i,
      /\bcontext\s+(?:storage|session|cookies)\s+(?:failed|error|invalid)\b/i,
      /\bcontext\s+(?:permissions|access)\s+(?:failed|error|denied)\b/i,
    ],
  };
}
