import { ErrorPatternGroup } from "../../../types/errorHandling/error-handler.types";

/**
 * ResourcePatterns - Resource & Logic Error Pattern Repository
 *
 * Contains error patterns for resource-related operations including
 * not found errors, conflicts, validation, parsing, and format errors.
 * Optimized for automation testing scenarios.
 */
export default class ResourcePatterns {
  public static readonly RESOURCE: ErrorPatternGroup = {
    category: "RESOURCE",
    context: "Resource & Logic Error",
    patterns: [
      // NOT_FOUND
      /\bresource\s+(?:not\s+found|missing|unavailable|doesn't\s+exist)\b/i,
      /\bfile\s+(?:not\s+found|missing|doesn't\s+exist)\b/i,
      /\bpath\s+(?:not\s+found|invalid|doesn't\s+exist)\b/i,
      /\bendpoint\s+(?:not\s+found|invalid|unavailable)\b/i,
      /\bapi\s+(?:not\s+found|unavailable|missing)\b/i,
      /\bservice\s+(?:not\s+found|unavailable|unreachable)\b/i,
      /\buser\s+(?:not\s+found|doesn't\s+exist|invalid)\b/i,
      /\brecord\s+(?:not\s+found|missing|doesn't\s+exist)\b/i,
      /\bentity\s+(?:not\s+found|missing|doesn't\s+exist)\b/i,
      /\bitem\s+(?:not\s+found|missing|doesn't\s+exist)\b/i,
      /\bmodel\s+(?:not\s+found|missing|doesn't\s+exist)\b/i,
      /\btemplate\s+(?:not\s+found|missing|doesn't\s+exist)\b/i,
      /\bmodule\s+(?:not\s+found|missing|cannot\s+resolve)\b/i,
      /\bpackage\s+(?:not\s+found|missing|unavailable)\b/i,
      /\b404\b|\bNOT_FOUND\b/i,
      /\bENOENT\b/i,
      /\bCannot\s+(?:find|locate|resolve)\b/i,
      /\bNo\s+such\s+(?:file|directory|resource|entity)\b/i,
      /\bUnable\s+to\s+(?:find|locate|resolve)\b/i,

      // CONFLICT
      /\bresource\s+(?:conflict|already\s+exists|duplicate)\b/i,
      /\bconflict\s+(?:detected|error|resolution)\b/i,
      /\bduplicate\s+(?:resource|entry|record|item)\b/i,
      /\balready\s+exists\b/i,
      /\bversion\s+conflict\b/i,
      /\bconcurrency\s+conflict\b/i,
      /\brace\s+condition\b/i,
      /\bstate\s+conflict\b/i,
      /\bmerge\s+conflict\b/i,
      /\bwrite\s+conflict\b/i,
      /\block\s+conflict\b/i,
      /\bupdate\s+conflict\b/i,
      /\bmodification\s+conflict\b/i,
      /\bsimultaneous\s+(?:access|modification|update)\b/i,
      /\b409\b|\bCONFLICT\b/i,
      /\bETAG\s+mismatch\b/i,
      /\bprecondition\s+failed\b/i,
      /\boptimistic\s+lock\s+(?:error|exception)\b/i,
      /\bresource\s+(?:locked|busy|in\s+use)\b/i,

      // VALIDATION
      /\bvalidation\s+(?:error|failed|failure)\b/i,
      /\binvalid\s+(?:input|data|format|value|parameter)\b/i,
      /\bvalidation\s+(?:rule|constraint)\s+(?:violated|failed)\b/i,
      /\brequired\s+(?:field|parameter|value)\s+(?:missing|not\s+provided)\b/i,
      /\bmissing\s+(?:required|mandatory)\s+(?:field|parameter|data)\b/i,
      /\bfield\s+(?:validation|error|invalid)\b/i,
      /\bschema\s+validation\s+(?:error|failed)\b/i,
      /\btype\s+validation\s+(?:error|failed)\b/i,
      /\bformat\s+validation\s+(?:error|failed)\b/i,
      /\brange\s+validation\s+(?:error|failed)\b/i,
      /\blength\s+validation\s+(?:error|failed)\b/i,
      /\bpattern\s+validation\s+(?:error|failed)\b/i,
      /\bemail\s+validation\s+(?:error|failed)\b/i,
      /\burl\s+validation\s+(?:error|failed)\b/i,
      /\bdate\s+validation\s+(?:error|failed)\b/i,
      /\bnumeric\s+validation\s+(?:error|failed)\b/i,
      /\bboolean\s+validation\s+(?:error|failed)\b/i,
      /\bstring\s+validation\s+(?:error|failed)\b/i,
      /\barray\s+validation\s+(?:error|failed)\b/i,
      /\bobject\s+validation\s+(?:error|failed)\b/i,
      /\bmust\s+be\s+(?:string|number|boolean|array|object)\b/i,
      /\bexpected\s+(?:string|number|boolean|array|object)\b/i,
      /\bdoes\s+not\s+match\s+(?:pattern|format|schema)\b/i,
      /\bvalue\s+(?:out\s+of\s+range|too\s+long|too\s+short)\b/i,
      /\b400\b|\bBAD_REQUEST\b/i,
      /\b422\b|\bUNPROCESSABLE_ENTITY\b/i,

      // PARSING
      /\bparse\s+(?:error|failed|failure)\b/i,
      /\bparsing\s+(?:error|failed|failure)\b/i,
      /\bsyntax\s+error\b/i,
      /\bmalformed\s+(?:data|input|format)\b/i,
      /\binvalid\s+(?:syntax|structure|format)\b/i,
      /\bexpected\s+(?:token|character|symbol)\b/i,
      /\bunexpected\s+(?:token|character|symbol|end\s+of\s+input)\b/i,
      /\bJSON\s+parse\s+(?:error|failed)\b/i,
      /\bXML\s+parse\s+(?:error|failed)\b/i,
      /\bYAML\s+parse\s+(?:error|failed)\b/i,
      /\bCSV\s+parse\s+(?:error|failed)\b/i,
      /\bSQL\s+parse\s+(?:error|failed)\b/i,
      /\bHTML\s+parse\s+(?:error|failed)\b/i,
      /\bMarkdown\s+parse\s+(?:error|failed)\b/i,
      /\bregex\s+parse\s+(?:error|failed)\b/i,
      /\bdate\s+parse\s+(?:error|failed)\b/i,
      /\bnumber\s+parse\s+(?:error|failed)\b/i,
      /\burl\s+parse\s+(?:error|failed)\b/i,
      /\bconfig\s+parse\s+(?:error|failed)\b/i,
      /\btemplate\s+parse\s+(?:error|failed)\b/i,
      /\bexpression\s+parse\s+(?:error|failed)\b/i,
      /\bquery\s+parse\s+(?:error|failed)\b/i,
      /\bparameter\s+parse\s+(?:error|failed)\b/i,
      /\bheader\s+parse\s+(?:error|failed)\b/i,
      /\bbody\s+parse\s+(?:error|failed)\b/i,
      /\bpayload\s+parse\s+(?:error|failed)\b/i,
      /\bmessage\s+parse\s+(?:error|failed)\b/i,
      /\btoken\s+parse\s+(?:error|failed)\b/i,
      /\bcertificate\s+parse\s+(?:error|failed)\b/i,
      /\bkey\s+parse\s+(?:error|failed)\b/i,
      /\bunterminated\s+(?:string|quote|comment|block)\b/i,
      /\bmissing\s+(?:closing|opening)\s+(?:bracket|brace|parenthesis|quote)\b/i,
      /\billegal\s+(?:character|token|escape)\b/i,
      /\binvalid\s+(?:character|token|escape|sequence)\b/i,
      /\bSyntaxError\b/i,
      /\bParseError\b/i,

      // FORMAT_ERROR (Automation Testing Focused)
      /\bformat\s+(?:error|invalid|unsupported|mismatch)\b/i,
      /\bformatting\s+(?:error|failed|invalid)\b/i,
      /\bencoding\s+(?:error|invalid|unsupported)\b/i,
      /\bcharset\s+(?:error|invalid|unsupported)\b/i,
      /\bmedia\s+type\s+(?:error|invalid|unsupported)\b/i,
      /\bcontent\s+type\s+(?:error|invalid|unsupported)\b/i,
      /\bMIME\s+type\s+(?:error|invalid|unsupported)\b/i,
      /\bfile\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bdata\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bdate\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\btime\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\btimestamp\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bnumber\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bemail\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\burl\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bURI\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bUUID\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bGUID\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bID\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bidentifier\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bversion\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bschema\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bprotocol\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bheader\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bpayload\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bmessage\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bresponse\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\brequest\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bquery\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bparameter\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\btoken\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bkey\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bcertificate\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bsignature\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bhash\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bchecksum\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bserialization\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bdeserialization\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\btransformation\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bconversion\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bexport\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bimport\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bvalidating\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bverifying\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\btesting\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bdebugging\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\blogging\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bmonitoring\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\btracking\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\btracing\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bconfiguring\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bprocessing\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bexecuting\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\brunning\s+format\s+(?:error|invalid|unsupported)\b/i,
      /\bhandling\s+format\s+(?:error|invalid|unsupported)\b/i,
    ],
  };
}
